server:
  port: 8082

spring:
  application:
    name: notification
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5432/notification
    username: islam

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka