spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411 #this is the default and you remove it
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER #lb short for load balancer (get url from eureka server)
          predicates:
            - Path=/api/v1/customer/**

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka